version: '3.6'

services: 
  proxy:
    image: nginx
    restart: always
    container_name: 'proxy'
    volumes:
      - ./nginx:/etc/nginx:ro
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.server.rule=Host(`jordanmoore.org`)'
      - 'traefik.http.routers.server.entrypoints=websecure'
      - 'traefik.http.routers.server.tls.certresolver=appresolve'
    depends_on:
      - app
      - admin
      - auth

  auth:
    build: ./jwt_server
    restart: always
    environment: 
      - PORT=4000
      - JWKS_URI=${JWKS_URI}
      - HOST_NAME=${HOST_NAME}

  db: 
    image: postgres:latest
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
    ports: 
      - 5432

  app:
    build: ./
    restart: always
    env_file:
      - ./.env
    depends_on: 
      - db
    ports:
      - 5433:5433
    command: ["--connection", "${DATABASE_URL}", "--port", "5433", "--schema", "public", "--append-plugins", "postgraphile-plugin-connection-filter", "--enhance-graphiql"]
    
  admin:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - db

volumes:
  db_data: